### ISSUE TITLE
Add support for SSL/TLS in SMTP server

### ISSUE THREAD

**Issue by carlos-wong** [overhangio/tutor#231]
Please post on our forums: https://discuss.overhang.io for questions about using `tutor`.

https://discuss.overhang.io/t/smtp-config-use/84

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker.

I am not sure it is a but or not? 
I am follow the doc https://docs.tutor.overhang.io/configuration.html#smtp.

But the lms_worker logs aways show raise SMTPServerDisconnected("Connection unexpectedly closed")

I curious about the ACTIVATE_SMTP, should I set to true ? I am configed true and false but the log are same.

I am checked https://github.com/overhangio/tutor/issues/215 and checked my config by use a test script to send email

**Comment by carlos-wong** [comment]
this is my test script: https://gist.github.com/carlos-wong/7a70e3f9fa3cbedca39686d32faddd71

**Comment by regisb** [comment]
Hi @carlos-wong! Thanks for the more detailed issue description :wink:

Did you modify the email configuration? If yes, how?

**Comment by carlos-wong** [comment]
Hi  @regisb , I edit the email config by modify the config.yml. Then save the config , and restart the services. I checking the version. I am followed the doc by install 3.4.3, now I am installing 3..5.3

**Comment by carlos-wong** [comment]
I am upgraded to 3.5.3 the result is same.

Here is the log

```
lms_worker_1      | Traceback (most recent call last):
lms_worker_1      |   File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 23, in send_activation_email
lms_worker_1      |     mail.send_mail(subject, message, from_address, [dest_addr], fail_silently=False)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
lms_worker_1      |     return mail.send()
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 348, in send
lms_worker_1      |     return self.get_connection(fail_silently).send_messages([self])
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
lms_worker_1      |     new_conn_created = self.open()
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open
lms_worker_1      |     self.connection = self.connection_class(self.host, self.port, **connection_params)
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
lms_worker_1      |     (code, msg) = self.connect(host, port)
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
lms_worker_1      |     (code, msg) = self.getreply()
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
lms_worker_1      |     raise SMTPServerDisconnected("Connection unexpectedly closed")
lms_worker_1      | SMTPServerDisconnected: Connection unexpectedly closed
lms_worker_1      | 2019-07-06 06:12:51,967 ERROR 1 [celery.worker.job] log.py:282 - Task student.tasks.send_activation_email[04d91b91-716f-4339-b10d-eb3baff394fb] raised unexpected: Exception()
lms_worker_1      | Traceback (most recent call last):
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
lms_worker_1      |     R = retval = fun(*args, **kwargs)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
lms_worker_1      |     return self.run(*args, **kwargs)
lms_worker_1      |   File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 50, in send_activation_email
lms_worker_1      |     raise Exception
lms_worker_1      | Exception
```

**Comment by regisb** [comment]
>  I edit the email config by modify the config.yml
So... I suppose you edited `SMTP_USERNAME`, `SMTP_PASSWORD`, `SMTP_HOST` and `SMTP_PORT`. Is that correct?

Your script uses SSL authentication for SMTP, and as you mentioned this is not supported (yet) by Tutor. So let's try to use SSL.

Please try the following:
1. Add `EMAIL_USE_SSL = True` to `env/apps/openedx/settings/lms/production.py` 
2. Restart lms worker: `tutor local restart lms_worker`
3. Try again.

Does it solve your problem?

**Comment by carlos-wong** [comment]
@carlos-wong yes. it is miss the ssl config. I just curious about the config.yml doc didn't describe the smtp ssl method.

**Comment by regisb** [comment]
Wait! Don't close this issue! This is probably a feature that we want to add to Tutor.

**Comment by regisb** [comment]
@carlos-wong Would you mind testing if email sending still works if you replace `EMAIL_USE_SSL` by `EMAIL_USE_TLS`? Those two settings are contradictory and I would rather implement just one of them.

**Comment by carlos-wong** [comment]
@regisb Hi, I am test on my smtp service. if I change to EMAIL_USE_TLS, it will fail

```
lms_worker_1      | Traceback (most recent call last):
lms_worker_1      |   File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 23, in send_activation_email
lms_worker_1      |     mail.send_mail(subject, message, from_address, [dest_addr], fail_silently=False)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
lms_worker_1      |     return mail.send()
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 348, in send
lms_worker_1      |     return self.get_connection(fail_silently).send_messages([self])
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
lms_worker_1      |     new_conn_created = self.open()
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open
lms_worker_1      |     self.connection = self.connection_class(self.host, self.port, **connection_params)
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
lms_worker_1      |     (code, msg) = self.connect(host, port)
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 317, in connect
lms_worker_1      |     (code, msg) = self.getreply()
lms_worker_1      |   File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
lms_worker_1      |     raise SMTPServerDisconnected("Connection unexpectedly closed")
lms_worker_1      | SMTPServerDisconnected: Connection unexpectedly closed
lms_worker_1      | 2019-07-07 14:30:10,001 ERROR 1 [celery.worker.job] log.py:282 - Task student.tasks.send_activation_email[6445a871-f4e7-483b-bdad-388d9a9ff663] raised unexpected: Exception()
lms_worker_1      | Traceback (most recent call last):
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
lms_worker_1      |     R = retval = fun(*args, **kwargs)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
lms_worker_1      |     return self.run(*args, **kwargs)
lms_worker_1      |   File "/openedx/edx-platform/common/djangoapps/student/tasks.py", line 50, in send_activation_email
lms_worker_1      |     raise Exception
lms_worker_1      | Exception
```

I think you should expose this two options let the user choose
