### ISSUE TITLE
version `OPENSSL_1.0.2' not found

### ISSUE THREAD

**Issue by khudkhud** [overhangio/tutor#240]
Hi regisb, 
Thank you for your excellent work!
There is some problems when I use Tutor, and I hope your help.

When I type the following command, I got an Import error.

```
$ tutor local quickstart
docker-compose -f /home/huwei/.local/share/tutor/env/local/docker-compose.yml --project-name 


$ tutor_local rm --stop --force
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 6, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/compose/cli/main.py", line 17, in <module>
    import docker
  File "/usr/local/lib/python3.5/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python3.5/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python3.5/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python3.5/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python3.5/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python3.5/dist-packages/docker/tls.py", line 2, in <module>
    import ssl
  File "/usr/lib/python3.5/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /tmp/_MEI1THoET/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /usr/lib/python3.5/lib-dynload/_ssl.cpython-35m-x86_64-linux-gnu.so)
Error: Command failed with status 1: docker-compose -f /home/huwei/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force
```

But when I enter the python environments directly and type 'import _ssl' and 'import ssl', there is no errors. 

```
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> import _ssl
>>> 
```

Do you have any advice to help me resolving this problem? Thank you very much!

**Comment by regisb** [comment]
Hi @khudkhud! This error seems related to your python install, and not to Tutor directly. Nonetheless, let's try to debug this. Please post the exact output of the following commands:

```
python --version
python3 --version
docker-compose --help
head /usr/local/bin/docker-compose
```

Please wrap the output in triple backticks (`` ``` ``), and not quote signs (`>`).

**Comment by khudkhud** [comment]
Thank you very much for your help!@regisb 

1. python --version
```
Python 3.6.4 :: Anaconda, Inc.
```
2. python3 --version
```
Python 3.6.4 :: Anaconda, Inc.
```
3. docker-compose --version
```
docker-compose version 1.24.1, build 4667896
```
4. head /usr/local/bin/docker-compose
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from compose.cli.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
5.  docker-compose --help
```
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
  --verbose                   Show more output
  --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  --no-ansi                   Do not print ANSI control characters
  -v, --version               Print version and exit
  -H, --host HOST             Daemon socket to connect to

  --tls                       Use TLS; implied by --tlsverify
  --tlscacert CA_PATH         Trust certs signed only by this CA
  --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
  --tlskey TLS_KEY_PATH       Path to TLS key file
  --tlsverify                 Use TLS and verify the remote
  --skip-hostname-check       Don't check the daemon's hostname against the
                              name specified in the client certificate
  --project-directory PATH    Specify an alternate working directory
                              (default: the path of the Compose file)
  --compatibility             If set, Compose will attempt to convert keys
                              in v3 files to their non-Swarm equivalent

Commands:
  build              Build or rebuild services
  bundle             Generate a Docker bundle from the Compose file
  config             Validate and view the Compose file
  create             Create services
  down               Stop and remove containers, networks, images, and volumes
  events             Receive real time events from containers
  exec               Execute a command in a running container
  help               Get help on a command
  images             List images
  kill               Kill containers
  logs               View output from containers
  pause              Pause services
  port               Print the public port for a port binding
  ps                 List containers
  pull               Pull service images
  push               Push service images
  restart            Restart services
  rm                 Remove stopped containers
  run                Run a one-off command
  scale              Set number of containers for a service
  start              Start services
  stop               Stop services
  top                Display the running processes
  unpause            Unpause services
  up                 Create and start containers
  version            Show the Docker-Compose version information
```

**Comment by ak00001** [comment]
Just making a guess here, as I ran into the same error. 
Could it be that the user needs to have sudo privileges for the docker-compose? Have you tried running `sudo tutor local quickstart`?

**Comment by regisb** [comment]
This issue is not related to a permission problem. Your version of docker-compose was installed for python 3.5 while you are running tutor with python 3.6. I believe the version mismatch causes the issue.
I suggest you uninstall docker-compose and re-install it following the official instructions.

**Comment by khudkhud** [comment]
> Just making a guess here, as I ran into the same error.
> Could it be that the user needs be added to the docker group/ have sudo privileges for the docker-compose? Have you tried running `sudo tutor local quickstart`?

Yes, I tried the command with `sudo`. Thank you!

> This issue is not related to a permission problem. Your version of docker-compose was installed for python 3.5 while you are running tutor with python 3.6. I believe the version mismatch causes the issue.
> I suggest you uninstall docker-compose and re-install it following the official instructions.

Thank you! I will have a try.

**Comment by khudkhud** [comment]
@regisb Thank you for your advice!
I uninstall docker-compose and re-install it following the official instructions, and it works.

By the way, I installed the docker-compose with pip before.
```
export LC_ALL=C
sudo pip install docker-compose
```
