### ISSUE TITLE
LMS migration crashes on k8s with ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol

### ISSUE THREAD

**Issue by zabudskyi** [overhangio/tutor#243]
Hi,
My test environment: 
tutor 3.6.2
k8s 1.15.2
```
pip3 install tutor-openedx
pip3 install tutor-minio

~/.local/bin/tutor plugins enable minio
~/.local/bin/tutor config save
~/.local/bin/tutor k8s quickstart
```
```
Finding pod name for lms deployment...
kubectl get --namespace openedx --selector=app.kubernetes.io/instance=openedx-2EmfGx7FQXwhz2z5A0ClGFJA,app.kubernetes.io/name=lms pods -o=jsonpath={.items[0].metadata.name}
kubectl exec --namespace openedx lms-6d5dfdc845-r5r7g -- sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
./manage.py lms --settings=tutor.production migrate

./manage.py lms --settings=tutor.production create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret NV60ObbyxIjM8kRjuZBzjPln \
    --trusted

# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
2019/08/16 07:44:02 Waiting for: tcp://mysql:3306
2019/08/16 07:44:02 Connected to tcp://mysql:3306
WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2019-08-16 07:44:07,562 WARNING 73 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2019-08-16 07:44:07,563 WARNING 73 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: admin, api_admin, assessment, auth, badges, block_structure, bookmarks, branding, bulk_email, catalog, celery_utils, certificates, commerce, completion, consent, content_type_gating, contentserver, contenttypes, cors_csrf, course_action_state, course_duration_limits, course_goals, course_groups, course_modes, course_overviews, courseware, crawlers, credentials, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, email_marketing, embargo, enterprise, entitlements, experiments, external_auth, grades, instructor_task, integrated_channel, lms_xblock, microsite_configuration, milestones, mobile_api, notes, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, programs, redirects, rss_proxy, sap_success_factors, schedules, self_paced, sessions, shoppingcart, site_configuration, sites, social_django, splash, static_replace, status, student, submissions, survey, teams, theming, third_party_auth, track, user_api, user_authn, util, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xapi, xblock_django
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying sites.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying api_admin.0001_initial... OK
  Applying api_admin.0002_auto_20160325_1604... OK
  Applying api_admin.0003_auto_20160404_1618... OK
  Applying api_admin.0004_auto_20160412_1506... OK
  Applying api_admin.0005_auto_20160414_1232... OK
  Applying api_admin.0006_catalog... OK
  Applying api_admin.0007_delete_historical_api_records... OK
  Applying assessment.0001_initial... OK
  Applying assessment.0002_staffworkflow... OK
  Applying assessment.0003_expand_course_id... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying instructor_task.0001_initial... OK
  Applying certificates.0001_initial... OK
  Applying certificates.0002_data__certificatehtmlviewconfiguration_data... OK
  Applying certificates.0003_data__default_modes...Traceback (most recent call last):
  File "./manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/openedx/edx-platform/lms/djangoapps/certificates/migrations/0003_data__default_modes.py", line 24, in forwards
    File(open(settings.PROJECT_ROOT / 'static' / 'images' / 'default-badges' / file_name))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/openedx/venv/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 409, in _save
    key = self.bucket.get_key(encoded_name)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 193, in get_key
    key, resp = self._get_key_internal(key_name, headers, query_args_l)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 200, in _get_key_internal
    query_args=query_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 665, in make_request
    retry_handler=retry_handler
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
command terminated with exit code 1
Error: Command failed with status 1: kubectl exec --namespace openedx lms-6d5dfdc845-r5r7g -- sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
./manage.py lms --settings=tutor.production migrate

./manage.py lms --settings=tutor.production create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret NV60ObbyxIjM8kRjuZBzjPln \
    --trusted

# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```

**Comment by zabudskyi** [comment]
@regisb 
Is there any workaround? Does it happen because HTTPS is disabled?
What can be done for further troubleshooting?
`~/.local/bin/tutor k8s logs lms`
```
kubectl logs --namespace openedx --selector=app.kubernetes.io/instance=openedx-8L6HXa7bSCYo1MSwsGIbP5Dx,app.kubernetes.io/name=lms
WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2019-08-21 08:52:57,761 WARNING 11 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2019-08-21 08:52:57,761 WARNING 10 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2019-08-21 08:52:57,761 WARNING 10 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2019-08-21 08:52:57,761 WARNING 11 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
```

**Comment by regisb** [comment]
Gi @zabudskyi! Unfortunately I'm currently on holidays, so I have little time to dedicate to this. I'll be able to work on it starting from the beginning of September. I hope that's ok with you?

**Comment by PavloZabudskyi** [comment]
@regisb Sure, have a great holiday. I'll try to setup it with https enabled meawhile.
There is no option to use self-signed issuer, letsencrypt only, right?
I had LMS certificate with Ready status `True` but still got `ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)`

**Comment by zabudskyi** [comment]
@regisb Sure, have a great holiday. I'll try to setup it with https enabled meawhile.
There is no option to use self-signed issuer, letsencrypt only, right?
I had LMS certificate with Ready status True but still got ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by regisb** [comment]
Hi @zabudskyi! I can finally try to address this issue. Did you check that the MinIO hostname (given by `tutor config printvalue MINIO_HOST`) points to your k8s cluster?

**Comment by zabudskyi** [comment]
Hi @regisb 
Yes, and I can access minio with web.
Though I go to 8088 port. It is ingress port.

**Comment by regisb** [comment]
Ingress does not listen to ports 80/443? I'm afraid this is a requirement, as far as Tutor is concerned.

**Comment by zabudskyi** [comment]
I see. Can it be fixed in k8s after this crash?
Are only migrations left? We can run migration commands for each component afterwards.
Do you plan to add possibility to use non-standard ports in future releases?

**Comment by regisb** [comment]
> Can it be fixed in k8s after this crash?

What do you mean? Can what be fixed?

> Are only migrations left? We can run migration commands for each component afterwards.

Migrations are some of the initialization scripts that are run to bootstrap all services.

>  Do you plan to add possibility to use non-standard ports in future releases?

No, unless I understand what kind of use case you are trying to realise.

**Comment by zabudskyi** [comment]
By fixing it I mean make it work after `k8s quickstart` fails manually(as we didn't meat requirements).
We got pods up and running so we can exec it with migration commands, change some code.
Probably it is not so trivial as it sound.

Our use case: 80/443 ports are used by ambassador so we can't use them for ingress.

**Comment by regisb** [comment]
> By fixing it I mean make it work after k8s quickstart fails manually(as we didn't meat requirements).

Pods are running, so I see no reason that you shouldn't be able to fix them by tweaking settings manually. It's not going to be easy though, and that's probably an understatement...

> Our use case: 80/443 ports are used by ambassador so we can't use them for ingress.

Basically, Open edX web services (LMS, CMS, MinIO, etc) need to be reachable through ports 80/443. Maybe you can configure Ambassador so that the right domain names can be accessed on these ports?
