### ISSUE TITLE
LMS migration crashes on k8s with django.db.utils.InternalError

### ISSUE THREAD

**Issue by zabudskyi** [overhangio/tutor#244]
Hi,
My test environment:
```
tutor 3.6.2
k8s 1.15.2
```
I enabled https to avoid https://github.com/overhangio/tutor/issues/243
Now I get 
```
./manage.py lms --settings=tutor.production migrate
WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2019-08-22 13:33:43,488 WARNING 1604 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2019-08-22 13:33:43,489 WARNING 1604 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.11/ref/databases/#mysql-sql-mode
Traceback (most recent call last):
  File "./manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 210, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema
    if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 55, in table_names
    return get_names(cursor)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/introspection.py", line 50, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/introspection.py", line 56, in get_table_list
    cursor.execute("SHOW FULL TABLES")
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.InternalError: (4, "Error on close of './openedx/enterprise_enterprisecustomer.frm' (Errcode: 2 - No such file or directory)")
```
`kubectl logs lms-7664f8564f-r6sw4`
```
2019-08-22 14:55:18,314 ERROR 10 [django.request] exception.py:135 - Internal Server Error: /
Traceback (most recent call last):
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/sites/middleware.py", line 12, in process_request
    request.site = get_current_site(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/contrib/sites/shortcuts.py", line 15, in get_current_site
    return Site.objects.get_current(request)
  File "/openedx/venv/local/lib/python2.7/site-packages/django_sites_extensions/models.py", line 44, in patched_get_current
    return self._get_site_by_id(settings.SITE_ID)  # pylint: disable=protected-access
  File "/openedx/venv/local/lib/python2.7/site-packages/django_sites_extensions/models.py", line 69, in patched_get_site_by_id
    site = self.get(pk=site_id)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Site matching query does not exist.
```

**Comment by regisb** [comment]
This is related to #243: for now, Tutor requires the Ingress server to listen to ports 80/443.
