### ISSUE TITLE
ERROR 2003 (HY000): Can't connect to MySQL server on "tutor k8s quickstart"

### ISSUE THREAD

**Issue by debianmaster** [overhangio/tutor#249]
**Bug description**
> When installing tutor on k8s
seeing this issue 
```
Initialising MySQL...
Warning: Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [1/10] Waiting for MySQL service (this may take a while)...
Warning: Using a password on the command line interface can be insecure.
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (110)
    [2/10] Waiting for MySQL service (this may take a while)...
Warning: Using a password on the command line interface can be insecure.
    [3/10] Waiting for MySQL service (this may take a while)...
```

**How to reproduce**
```
tutor k8s quickstart
```

**Environment**
Mac

**Additional context**

**Comment by regisb** [comment]
Hi @debianmaster! Sorry for the delay in answering this issue, this flew under my radar somehow.

What is the state of the mysql container? This kind of issue may appear for many different reasons. For instance, the docker image may be downloading, or the kubernetes cluster may not have enough memory.

**Comment by debianmaster** [comment]
@regisb   looks like this dns is not resolved correctly inside container.    when i add .  mysql  /etc/hosts . entries it works fine, i will try to get more details

**Comment by regisb** [comment]
@debianmaster Please update this issue with your findings when you have more information.

**Comment by debianmaster** [comment]
i had to do this and re-run installer to fix the error
```sh
➜  edx k -n openedx exec -it mysql-9fb489cb-6v6qj sh
# echo "127.0.0.1 mysql" >> /etc/hosts
# exit
```

**Comment by RajputVaibhav** [comment]
I'm trying to work with tutor k8s quickstart as well, but the lms worker pod keeps going into CrashLoopBackOff and hence I get stuck at `Waiting for a mysql pod to be ready...`. On viewing the logs of the lms worker, I get the following error
`django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' (111)")`

**Comment by regisb** [comment]
@RajputVaibhav please investigate more thoroughly and answer the questions I asked above.

**Comment by RajputVaibhav** [comment]
@regisb i traced it back and it seems like minio isn't creating a persistent volume. 
The persistent volume claim used by mysql is pending due to the following reason
`no persistent volumes available for this claim and no storage class is set`

**Comment by RajputVaibhav** [comment]
I have manually created persistent volumes and the claims are getting bound to it. The error has changed to the following

**Error Log**
```
$ kubectl logs lms-worker-689856cf9-5wwfp  -n openedx

WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-04-15 07:58:29,522 WARNING 1 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-04-15 07:58:29,522 WARNING 1 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
Traceback (most recent call last):
  File "./manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/djcelery/management/commands/celery.py", line 21, in run_from_argv
    ['{0[0]} {0[1]}'.format(argv)] + argv[2:],
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/worker/__init__.py", line 95, in __init__
    self.app.loader.init_worker()
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/loaders/base.py", line 128, in init_worker
    self.import_default_modules()
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/loaders/base.py", line 116, in import_default_modules
    signals.import_modules.send(sender=self.app)
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/fixups/django.py", line 73, in on_import_modules
    self.worker_fixup.validate_models()
  File "/openedx/venv/local/lib/python2.7/site-packages/celery/fixups/django.py", line 173, in validate_models
    cmd.check()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 1284, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/base.py", line 1359, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 913, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 219, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 322, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 49, in check_field
    field_type = field.db_type(self.connection)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 644, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 174, in data_types
    if self.features.supports_microsecond_precision:
  File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/features.py", line 53, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 385, in mysql_version
    with self.temporary_connection() as cursor:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 591, in temporary_connection
    cursor = self.cursor()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'openedx'@'10.244.2.47' (using password: YES)")
```

**Comment by regisb** [comment]
https://github.com/overhangio/tutor/issues/249#issuecomment-613882007

**Comment by RajputVaibhav** [comment]
Mysql container is in running state, lms and lms-worker containers are in Error state
lms container has following logs 

```
WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-04-15 09:14:26,725 WARNING 10 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-04-15 09:14:26,725 WARNING 12 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-04-15 09:14:26,725 WARNING 10 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-04-15 09:14:26,725 WARNING 12 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
```

Error log for lms-worker container can be viewed in https://github.com/overhangio/tutor/issues/249#issuecomment-613882007

**Comment by RajputVaibhav** [comment]
After multiple attempts to restart, the lms-worker pod is switching between
`django.db.utils.OperationalError: (2005, "Unknown MySQL server host 'mysql' (0)")`
and 
`django.db.utils.OperationalError: (1045, "Access denied for user 'openedx'@'10.244.2.47' (using password: YES)")`
The MySQL pod stays in Running state with the following logs
```
$ kubectl logs mysql-558544ccf9-cr9z2 -n openedx
2020-04-15 09:13:29 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2020-04-15 09:13:29 0 [Note] mysqld (mysqld 5.6.36) starting as process 1 ...
```

**Comment by RajputVaibhav** [comment]
After trying  https://github.com/overhangio/tutor/issues/249#issuecomment-535558040 solution. The lms-worker is running successfully but on running `tutor k8s quickstart` again, I got the following error
```
Error: Command failed with status 137: kubectl exec --namespace openedx lms-5db54cbd7f-gwmc4 -- sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
```

On viewing logs, I can see
```
WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
  warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)

2020-04-16 05:14:08,344 WARNING 11 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-04-16 05:14:08,344 WARNING 11 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
2020-04-16 05:14:08,520 WARNING 10 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
2020-04-16 05:14:08,520 WARNING 10 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
```

**Comment by RajputVaibhav** [comment]
This seems like a different error, so I am opening a new issue for it
