### ISSUE TITLE
xblock load fail

### ISSUE THREAD

**Issue by carlos-wong** [overhangio/tutor#252]
**Bug description**
I testing https://github.com/ruslan-simonenko/xblock-scratch, this xblock could load and work use xblock-sdk env https://github.com/edx/xblock-sdk.git. But when I am add to tutor, rebuild image the xblock load fail. By the way the example is work fine (https://github.com/open-craft/xblock-poll)
 

the container is work fine:

```
[25/Sep/2019 06:40:50] "GET /container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e HTTP/1.1" 200 78785
[25/Sep/2019 06:40:50] "GET /static/studio/common/css/vendor/editImageModal.min.css HTTP/1.1" 304 0
[25/Sep/2019 06:40:50] "GET /static/studio/common/js/vendor/popper.js HTTP/1.1" 404 1718
[25/Sep/2019 06:40:50] "GET /static/studio/common/js/vendor/editImageModal.min.js HTTP/1.1" 304 0
[25/Sep/2019 06:40:50] "GET /static/studio/bundles/js/factories/container.js HTTP/1.1" 304 0
[25/Sep/2019 06:40:50] "GET /static/studio/common/js/vendor/bootstrap.js HTTP/1.1" 404 1727
[25/Sep/2019 06:40:51] "GET /static/studio/common/js/vendor/editImageModal.min.js.map HTTP/1.1" 304 0
[25/Sep/2019 06:40:51] "GET /static/studio/bundles/js/factories/container.js.map HTTP/1.1" 304 0
2019-09-25 06:40:51,393 INFO 122 [tracking] logger.py:50 - {"username": "carlos-wong", "event_type": "/xblock/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e/container_preview", "ip": "183.14.134.226", "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36", "host": "openedxdev.lejuhub.com:8001", "referer": "http://openedxdev.lejuhub.com:8001/container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e", "accept_language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7", "event": "{\"POST\": {}, \"GET\": {\"_\": [\"1569393650624\"]}}", "event_source": "server", "context": {"user_id": 7, "org_id": "", "course_id": "", "path": "/xblock/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e/container_preview"}, "time": "2019-09-25T06:40:51.393761+00:00", "page": null}
[25/Sep/2019 06:40:51] "GET /xblock/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e/container_preview?_=1569393650624 HTTP/1.1" 200 962783
2019-09-25 06:40:52,004 INFO 122 [tracking] logger.py:50 - {"username": "carlos-wong", "event_type": "/xblock/container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e", "ip": "183.14.134.226", "agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36", "host": "openedxdev.lejuhub.com:8001", "referer": "http://openedxdev.lejuhub.com:8001/container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e", "accept_language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7", "event": "{\"POST\": {}, \"GET\": {}}", "event_source": "server", "context": {"user_id":
7, "org_id": "", "course_id": "", "path": "/xblock/container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e"}, "time": "2019-09-25T06:40:52.004230+00:00", "page": null}
[25/Sep/2019 06:40:52] "GET /xblock/container/block-v1:leju_org+test+2019-08+type@vertical+block@68b65ff7795e41f1872eed957712a00e HTTP/1.1" 200 24696
```

but the web-brower(chrome) notify error:

```
backend.js:6 TypeError: Cannot set property 'lists' of undefined
    at eval (eval at globalEval (jquery.js:343), <anonymous>:6:21)
    at eval (<anonymous>)
    at Function.globalEval (jquery.js:343)
    at domManip (jquery.js:5291)
    at jQuery.fn.init.append (jquery.js:5431)
    at child.loadResource (xblock.js:223)
    at applyResource (xblock.js:189)
    at Object.<anonymous> (xblock.js:192)
    at fire (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246) "TypeError: Cannot set property 'lists' of undefined
    at eval (eval at globalEval (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:343:5), <anonymous>:6:21)
    at eval (<anonymous>)
    at Function.globalEval (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:343:5)
    at domManip (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:5291:15)
    at jQuery.fn.init.append (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:5431:10)
    at child.loadResource (http://openedxdev.lejuhub.com:8001/static/studio/bundles/commons.js:5052:27)
    at applyResource (http://openedxdev.lejuhub.com:8001/static/studio/bundles/commons.js:5018:36)
    at Object.<anonymous> (http://openedxdev.lejuhub.com:8001/static/studio/bundles/commons.js:5021:25)
    at fire (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:3187:31)
    at Object.add [as done] (http://openedxdev.lejuhub.com:8001/static/studio/common/js/vendor/jquery.js:3246:7)"
```

**How to reproduce**

**Environment**

tutor, version 3.7.0

**Additional context**

**Comment by carlos-wong** [comment]
reproduce: follow https://docs.tutor.overhang.io/configuration.html?highlight=xblock#installing-extra-xblocks-and-requirements

**Comment by regisb** [comment]
Hi @carlos-wong! This looks like an upstream error in the Scratch xblock. The error occurs in the client-side code, so it does not look like a tutor-related issue. Also, the XBlock-Scratch xblock was not updated in 3 years, so it's unlikely that the xblock is compatible with Ironwood.

I suggest you create a new issue on the xblock repo and talk directly to the xblock author about it: https://github.com/ruslan-simonenko/xblock-scratch/issues Feel free to link to this issue here.
