### ISSUE TITLE
An HTTP request took too long to complete. Retry with --verbose to obtain debug info

### ISSUE THREAD

**Issue by lucasfersilva** [overhangio/tutor#281]
Hello guys, I'm trying to run tutor on an ssh machine that has Ubuntu 18.04.3 LTS, and I got into a problem that I cannot solve, I'm trying to run but I always get the error after the configuration

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Error: Command failed with status 1: docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force

```
my connection is not slow and I really don't know why I'm getting this, does someone have an idea?
when I run --verbose up I get this error:

```

root@elearning:~/.local/share/tutor/env/local# docker-compose --verbose up
compose.config.config.find: Using configuration files: ./docker-compose.yml
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 421, in _make_request
  File "<string>", line 3, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 416, in _make_request
  File "http/client.py", line 1336, in getresponse
  File "http/client.py", line 306, in begin
  File "http/client.py", line 267, in _read_status
  File "socket.py", line 589, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 720, in urlopen
  File "site-packages/urllib3/util/retry.py", line 400, in increment
  File "site-packages/urllib3/packages/six.py", line 735, in reraise
  File "site-packages/urllib3/connectionpool.py", line 672, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 423, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 125, in perform_command
  File "compose/cli/command.py", line 64, in project_from_options
  File "compose/cli/command.py", line 147, in get_project
  File "compose/cli/command.py", line 121, in get_client
  File "site-packages/docker/api/daemon.py", line 181, in version
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 230, in _get
  File "site-packages/requests/sessions.py", line 546, in get
  File "site-packages/requests/sessions.py", line 533, in request
  File "site-packages/requests/sessions.py", line 646, in send
  File "site-packages/requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
[18642] Failed to execute script docker-compose

```

**Comment by regisb** [comment]
Hi @lucasfersilva! As you discovered, this is not an issue related to Tutor, but to Docker and docker-compose. In my experience, this happens on machines with insufficient CPU or RAM. What are the specs of this particular machine?

**Comment by lucasfersilva** [comment]
hello @regisb 
those are the specs
          description: CPU
          product: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
          vendor: Intel Corp.
          physical id: 401
          bus info: cpu@0
          slot: CPU 1
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke md_clear
     *-memory
          description: System Memory
          physical id: 1000
          size: 1GiB
          capacity: 1GiB
          capabilities: ecc
          configuration: errordetection=multi-bit-ecc
        *-bank
             description: DIMM RAM
             physical id: 0
             slot: DIMM 0
             size: 1GiB
             width: 64 bits

**Comment by regisb** [comment]
> size: 1GiB
Is that the amount of ram you have? You need at least 4Gb https://docs.tutor.overhang.io/install.html#requirements

**Comment by lucasfersilva** [comment]
yes, its a free droplet

**Comment by lucasfersilva** [comment]
Thank you regis, I will fix that !!! ty
