### ISSUE TITLE
Workers fail to initialize on using quickstart

### ISSUE THREAD

**Issue by cemal-efe-g** [overhangio/tutor#285]
**Bug description**
I have been tracking the local quickstart tutorial and I get the exception provided below when I am trying to start the docker containers.

```
cms_worker_1      | Traceback (most recent call last):
cms_worker_1      |   File "./manage.py", line 119, in <module>
cms_worker_1      |     startup = importlib.import_module(edx_args.startup)
cms_worker_1      |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
cms_worker_1      |     __import__(name)
cms_worker_1      |   File "/openedx/edx-platform/cms/startup.py", line 9, in <module>
cms_worker_1      |     settings.INSTALLED_APPS  # pylint: disable=pointless-statement
cms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
cms_worker_1      |     self._setup(name)
cms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup   cms_worker_1      |     self._wrapped = Settings(settings_module)
cms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__cms_worker_1      |     mod = importlib.import_module(self.SETTINGS_MODULE)
cms_worker_1      |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
cms_worker_1      |     __import__(name)
cms_worker_1      | ImportError: No module named tutor.production
tutor_local_cms_worker_1 exited with code 1
lms_worker_1      | Traceback (most recent call last):
lms_worker_1      |   File "./manage.py", line 119, in <module>
lms_worker_1      |     startup = importlib.import_module(edx_args.startup)
lms_worker_1      |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
lms_worker_1      |     __import__(name)
lms_worker_1      |   File "/openedx/edx-platform/lms/startup.py", line 9, in <module>
lms_worker_1      |     settings.INSTALLED_APPS  # pylint: disable=pointless-statement
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
lms_worker_1      |     self._setup(name)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup   lms_worker_1      |     self._wrapped = Settings(settings_module)
lms_worker_1      |   File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__lms_worker_1      |     mod = importlib.import_module(self.SETTINGS_MODULE)
lms_worker_1      |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
lms_worker_1      |     __import__(name)
lms_worker_1      | ImportError: No module named tutor.production
tutor_local_lms_worker_1 exited with code 1
```

**How to reproduce**
I have used the quickstart command to initialize the containers and environment.

**Environment**
I am running Ubuntu 18.04 on WSL. My tutor version is 3.11.3.

**Additional context**
I really can't understand if this is an issue from openEdx docker build or tutor.

**Comment by regisb** [comment]
Hi @cemal-efe-g! Have you customized your environment in any way? For instance, are you running a local fork of edx-platform? I'm asking because this is not the behaviour that I observe in production.

**Comment by cemal-efe-g** [comment]
I haven't modified the enviroment in any way. I can only note that, I forgot to give Docker enough RAM when I first initialized the enviroment. I cleaned up all the files in the generated enviroment folder, after Docker crashed mid-operation.

**Comment by regisb** [comment]
You did run the `tutor local quickstart` command after you deleted the environment, right?

**Comment by cemal-efe-g** [comment]
Yes, I ran it after deleting the enviroment

**Comment by regisb** [comment]
1. Is the error also occurring for the lms and cms containers? (and not just the worker containers)
2. Please paste here the *complete* output of the following commands:

    tutor local stop
    tutor config save
    tutor local run lms_worker cat lms/envs/tutor/production.py

(feel free to obfuscate any password or secret key from the output)

**Comment by cemal-efe-g** [comment]
1- They also have issues. Here is the lms container:
```
Traceback (most recent call last):
File "/openedx/venv/bin/gunicorn", line 11, in <module>
sys.exit(run())
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
super(Application, self).run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
Arbiter(self).run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
self.halt(reason=inst.reason, exit_status=inst.exit_status)
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
self.stop()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
time.sleep(0.1)
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
self.reap_workers()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```
Here is the cms container:
```
Traceback (most recent call last):
File "/openedx/venv/bin/gunicorn", line 11, in <module>
sys.exit(run())
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
super(Application, self).run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
Arbiter(self).run()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
self.halt(reason=inst.reason, exit_status=inst.exit_status)
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
self.stop()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
time.sleep(0.1)
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
self.reap_workers()
File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```
I thought the main issue was the workers due to these logs.

2- Here is the full logs of the commands I've put in.

```
cemal-efe-g@DESKTOP-0COE5NO:~$ tutor local stop
docker-compose -f /home/cemal-efe-g/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local rm --stop --force
Stopping tutor_local_lms_worker_1    ... done
Stopping tutor_local_nginx_1         ... done                                                                           
Stopping tutor_local_lms_1           ... done
Stopping tutor_local_cms_worker_1    ... done
Stopping tutor_local_cms_1           ... done
Stopping tutor_local_forum_1         ... done
Stopping tutor_local_memcached_1     ... done
Stopping tutor_local_elasticsearch_1 ... done
Stopping tutor_local_mongodb_1       ... done
Stopping tutor_local_smtp_1          ... done
Stopping tutor_local_mysql_1         ... done
Stopping tutor_local_rabbitmq_1      ... done
Going to remove tutor_local_lms_worker_1, tutor_local_nginx_1, tutor_local_lms_1, tutor_local_cms_worker_1, tutor_local_cms_1, tutor_local_forum_1, tutor_local_openedx-assets_1, tutor_local_memcached_1, tutor_local_elasticsearch_1, tutor_local_mongodb_1, tutor_local_smtp_1, tutor_local_mysql_1, tutor_local_rabbitmq_1
Removing tutor_local_lms_worker_1     ... done 
Removing tutor_local_nginx_1          ... done 
Removing tutor_local_lms_1            ...
Removing tutor_local_cms_worker_1     ... done 
Removing tutor_local_lms_1            ... done
Removing tutor_local_forum_1          ... done
Removing tutor_local_cms_1            ... done
Removing tutor_local_openedx-assets_1 ... done 
Removing tutor_local_elasticsearch_1  ... done
Removing tutor_local_mongodb_1        ... done
Removing tutor_local_smtp_1           ... done
Removing tutor_local_mysql_1          ... done
Removing tutor_local_rabbitmq_1       ... done
WARNING: Connection pool is full, discarding connection: 127.0.0.1
WARNING: Connection pool is full, discarding connection: 127.0.0.1
cemal-efe-g@DESKTOP-0COE5NO:~$  tutor config save
Configuration saved to /home/cemal-efe-g/.local/share/tutor/config.yml
Environment generated in /home/cemal-efe-g/.local/share/tutor/env
cemal-efe-g@DESKTOP-0COE5NO:~$  tutor local run lms_worker cat lms/envs/tutor/production.py
docker-compose -f /home/cemal-efe-g/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms_worker cat lms/envs/tutor/production.py
Creating tutor_local_rabbitmq_1      ... done
Creating tutor_local_smtp_1          ... done
Creating tutor_local_memcached_1     ... done
Creating tutor_local_mongodb_1       ... done
Creating tutor_local_mysql_1         ... done
Creating tutor_local_elasticsearch_1 ... done
Creating tutor_local_forum_1         ... done
Creating tutor_local_lms_1           ... done
cat: lms/envs/tutor/production.py: No such file or directory
Error: Command failed with status 1: docker-compose -f /home/cemal-efe-g/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms_worker cat lms/envs/tutor/production.py
```

**Comment by regisb** [comment]
Error: Command failed with status 1: docker-compose -f /home/cemal-efe-g/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms_worker cat lms/envs/tutor/production.py

Now that's surprising.

Please paste here the output of:

```
ls -l "$(tutor config printroot)/env/apps/settings/lms"
tutor local run lms_worker ls lms/ lms/envs/ lms/envs/tutor
```

**Comment by cemal-efe-g** [comment]
Here:
```
cemal-efe-g@DESKTOP-0COE5NO:~$ ls -l "$(tutor config printroot)/env/apps/settings/lms"
ls: cannot access '/home/cemal-efe-g/.local/share/tutor/env/apps/settings/lms': No such file or directory
cemal-efe-g@DESKTOP-0COE5NO:~$ tutor local run lms_worker ls lms/ lms/envs/ lms/envs/tutor
docker-compose -f /home/cemal-efe-g/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local run --rm lms_worker ls lms/ lms/envs/ lms/envs/tutor
Starting tutor_local_rabbitmq_1      ... done
Starting tutor_local_memcached_1     ... done
Starting tutor_local_smtp_1          ... done
Starting tutor_local_mongodb_1       ...
Starting tutor_local_mongodb_1       ... done
Starting tutor_local_smtp_1          ... done
Starting tutor_local_forum_1         ... done
Starting tutor_local_lms_1           ... done
lms/:
README.rst    celery.py   envs        startup.pyc  tests.py  wsgi_apache_lms.py
__init__.py   celery.pyc  lib         static       urls.py
__init__.pyc  djangoapps  startup.py  templates    wsgi.py

lms/envs/:
__init__.py                bok_choy_docker.env.json  help_tokens.ini
__init__.pyc               bok_choy_docker.py        load_test.py
acceptance.py              common.py                 openstack.py
acceptance_docker.py       common.pyc                production.py
aws.py                     devstack.py               static.py
bok_choy.auth.json         devstack_docker.py        test.py
bok_choy.env.json          devstack_optimized.py     test_static_optimized.py
bok_choy.py                devstack_with_worker.py   tutor
bok_choy_docker.auth.json  docs

lms/envs/tutor:
```

**Comment by regisb** [comment]
Hmmm I wrote the first command incorrectly. Please run:

    ls -l "$(tutor config printroot)/env/apps/openedx/settings/lms"

Sorry about the back-and-forth. I'm honestly trying to figure out what's going on here.

**Comment by cemal-efe-g** [comment]
Same with me, I did a lot of research prior to opening to this issue but couldn't get anything working.
Here:
```
cemal-efe-g@DESKTOP-0COE5NO:~$ ls -l "$(tutor config printroot)/env/apps/openedx/settings/lms"
total 8
-rw-rw-rw- 1 cemal-efe-g cemal-efe-g    0 Feb  7 20:33 __init__.py
-rw-rw-rw- 1 cemal-efe-g cemal-efe-g 3057 Feb  7 20:33 development.py
-rw-rw-rw- 1 cemal-efe-g cemal-efe-g 3163 Feb  7 20:33 production.py
```

**Comment by cacciaresi** [comment]
@regisb in this comment: https://github.com/overhangio/tutor/issues/285#issuecomment-583646218 at the end of the pasted output this directory: `lms/envs/tutor` seems to be empty when it should be something like: 

```
lms/envs/tutor:
__init__.py   common.py       development.pyc  production.pyc
__init__.pyc  development.py  production.py
```

Just wanted to comment about that ;)

**Comment by regisb** [comment]
@cacciaresi yes, I noticed that.
@cemal-efe-g wait, I just noticed that you are running on WSL. I believe this may be linked to a problem with docker running on Windows. Did you manage to successfully bind-mount volumes in docker-compose-managed projects before?

**Comment by cemal-efe-g** [comment]
Bind-mounting normally works when you change your mount folder to root=/ in WSL. I have it currently setup like that.

**Comment by regisb** [comment]
> Bind-mounting normally works when you change your mount folder to root=/ in WSL

I did not understand that.

As you may have noticed, the `tutor/env/local/docker-compose.yml` file is supposed to mount the tutor settings inside the docker containers by way of relative path bind-mounts: https://github.com/overhangio/tutor/blob/master/tutor/templates/local/docker-compose.yml#L113

```
      - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/
      - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/
```

In your case, these bind-mounts are not happening, as @cacciaresi highlighted in his comment: https://github.com/overhangio/tutor/issues/285#issuecomment-583839743

You need to figure out how to configure WSL such that these relative path bind-mounts are happening. Unfortunately I cannot help you here because I do not run Windows (hence the lack of official support). But I would like to, so when you do manage to fin a solution, please post it here.

**Comment by cemal-efe-g** [comment]
Hi @regisb. So I managed to fix the bind-mounts and a few other errors that popped up during the installation. I am going to note bullet points for now and then going to close the issue. I also want to provide a detailed installation process after I check the steps more carefully. Here is the essence of it if anyone needs it right now:

1. You have to set the root folder in the `/etc/wsl.conf` to be `/` to let Docker understand where the bind mounts are, as stated in [this tutorial].(https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly) You also have to enable [file sharing](https://docs.docker.com/docker-for-windows/#file-sharing) from Docker dashboard as it does not ask to do this automatically, like it does when you bind-mount from a Windows Shell.
2. You have to initialize the the tutor enviroment under one of the folders in `$HOME` of the currently signed in **Windows User** (e.g. /c/Users/USER/tutor) as mounting other paths resulted in empty mounts inside containers. More on this [here](https://stackoverflow.com/a/56736935/12877774). Maybe trying again with sudo might fix, not sure. This also meant that I had to call all of the tutor commands in the *root directory* not in `/home/usr` as otherwise docker started the containers in `/home/usr/$GIVEN_PATH` instead of `$GIVEN_PATH` which broke stuff.
3. 4 GB of RAM just didn't cut it for me. Might be related to my computer, but worthwile to note for further investigation as minimal requirements might be higher.

**Comment by regisb** [comment]
Thanks a lot for your feedback @cemal-efe-g, this is useful stuff.
