### ISSUE TITLE
Quickstart Installation fails at migration consent.0001_initial

### ISSUE THREAD

**Issue by nahakiole** [overhangio/tutor#286]
**Bug description**
Can't install OpenEDX with quickstart
```
Applying consent.0001_initial...Killed
Error: Command failed with status 137: docker-compose -f /home/edx/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local exec lms sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms migrate

./manage.py lms create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret wFaD5fdxiSIZcNx4afQY27CZ \
    --trusted

# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```

**How to reproduce**
Run ```sudo tutor local quickstart```

**Environment**
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-66-generic x86_64)
Linux ubuntu-s-2vcpu-2gb-fra1-01 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by regisb** [comment]
Hi @nahakiole! You actually have two issues:
1. You should *not* be running tutor with `sudo`. See the explanations here: https://discuss.overhang.io/t/why-we-should-not-use-sudo-tutor-local-quickstart/219
2. 137 errors are usually related to out-of-memory errors. See for instance this report: https://discuss.overhang.io/t/error-command-failed-with-status-137/151/2 How much RAM do you have on this computer?

**Comment by nahakiole** [comment]
Wow, that was really fast 😄 I've now changed it to run without sudo, but it could also be a ram related problem. The server I ran it on only had 4 gigabytes. I wonder though why the installer needs so much ram? And that are just the migrations? 

I've also tried running the installer on my macbook but also failed with the same error and my macbook has 16 gigabytes of ram, so I wonder if that really is the issue?

**Comment by regisb** [comment]
The database migrations are notorious for eating up a lot of memory, for a reason that eludes me. There should be at least 4Gb RAM dedicated just to the Open edX platform, so if you have other software running at the same time it might not be enough.
On Mac OS the docker service allocates just 4Gb to the containers. See this section from the docs: https://docs.tutor.overhang.io/troubleshooting.html#running-migrations-killed

**Comment by regisb** [comment]
@nahakiole Did you manage to solve your problem? If yes, please close this issue.

**Comment by nahakiole** [comment]
I haven't had time to try it out and I might go with a simpler solution as I have found the edx project to be a bit too much for my requirements. 

What I think would help other people would be a notice when you start the container that they might have to increase the memory or even have the script do that automatically if the user wishes to do so.

**Comment by nahakiole** [comment]
I tried it again with more memory and now I think it's a different error:
```
Operations to perform:
  Apply all migrations: admin, api_admin, assessment, auth, badges, block_structure, bookmarks, branding, bulk_email, catalog, celery_utils, certificates, commerce, completion, consent, content_type_gating, contentserver, contenttypes, cors_csrf, course_action_state, course_duration_limits, course_goals, course_groups, course_modes, course_overviews, courseware, crawlers, credentials, credit, dark_lang, database_fixups, degreed, django_comment_common, django_notify, django_openid_auth, djcelery, edx_oauth2_provider, edx_proctoring, edxval, email_marketing, embargo, enterprise, entitlements, experiments, external_auth, grades, instructor_task, integrated_channel, lms_xblock, microsite_configuration, milestones, mobile_api, notes, oauth2, oauth2_provider, oauth_dispatch, oauth_provider, organizations, programs, redirects, rss_proxy, sap_success_factors, schedules, self_paced, sessions, shoppingcart, site_configuration, sites, social_django, splash, static_replace, status, student, submissions, survey, teams, theming, third_party_auth, track, user_api, user_authn, util, verified_track_content, verify_student, video_config, video_pipeline, waffle, waffle_utils, wiki, workflow, xapi, xblock_django
Running migrations:
  Applying credit.0004_delete_historical_credit_records...Traceback (most recent call last):
  File "./manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 156, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 487, in remove_field
    self.execute(sql)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 136, in execute
    cursor.execute(sql, params)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/openedx/venv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1091, "Can't DROP 'course_id'; check that column/key exists")
Error: Command failed with status 1: docker-compose -f /Users/robin/Library/Application Support/tutor/env/local/docker-compose.yml --project-name tutor_local exec lms sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms migrate

./manage.py lms create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret 84D3AfN3riyvKGi6XfmBo2p0 \
    --trusted

# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```

**Comment by nahakiole** [comment]
I've removed all the containers before running the command again.

**Comment by regisb** [comment]
You now have a corrupt MySQL database because the migrations crashed halfway. The fix is the same as here: https://discuss.overhang.io/t/error-on-ecommerce-launch/133/7 Just stop the platform and delete the base before running quickstart again:

```
tutor local stop
sudo rm -rf "$(tutor config printroot)/data/mysql"
tutor local quickstart
```

**Comment by nahakiole** [comment]
Thank you, now it's working. :) I think if you added the error message to the documentation that would help a lot already.  Also a guide how you have to remove the machines if the installation fails would be helpful.
