### ISSUE TITLE
Tutor gives ExternalReferenceForbidden error while running migrations

### ISSUE THREAD

**Issue by RajputVaibhav** [overhangio/tutor#317]
**Bug description**
Trying to run Tutor on AWS EKS (Kubernetes version: 1.14). Using Route 53 for lms domain name. on running `tutor k8s quickstart` got the below mentioned error 
```Running migrations:
  Applying certificates.0003_data__default_modes...Traceback (most recent call last):
  File "./manage.py", line 123, in <module>
    execute_from_command_line([sys.argv[0]] + django_args)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/openedx/edx-platform/lms/djangoapps/certificates/migrations/0003_data__default_modes.py", line 24, in forwards
    File(open(settings.PROJECT_ROOT / 'static' / 'images' / 'default-badges' / file_name))
  File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 94, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/openedx/venv/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 417, in _save
    self._save_content(key, content, headers=headers)
  File "/openedx/venv/local/lib/python2.7/site-packages/storages/backends/s3boto.py", line 428, in _save_content
    rewind=True, **kwargs)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 665, in make_request
    retry_handler=retry_handler
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/exception.py", line 296, in __init__
    super(StorageResponseError, self).__init__(status, reason, body)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/exception.py", line 115, in __init__
    h.parseString(self.body)
  File "/openedx/venv/local/lib/python2.7/site-packages/boto/handler.py", line 60, in parseString
    return self.parser.parse(StringIO(content))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/openedx/venv/local/lib/python2.7/site-packages/defusedxml/expatreader.py", line 44, in defused_external_entity_ref_handler
    raise ExternalReferenceForbidden(context, base, sysid, pubid)
defusedxml.common.ExternalReferenceForbidden: ExternalReferenceForbidden(system_id='http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd', public_id=-//W3C//DTD XHTML 1.0 Strict//EN)
command terminated with exit code 1
Error: Command failed with status 1: kubectl exec --namespace openedx lms-77fffd9854-b5gpv -- sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms migrate

./manage.py lms create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret toxLSMn9YPEBWxcNPTi6mOsZ \
    --trusted
    
# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```
**How to reproduce**
`tutor k8s quickstart`

**Environment**
Running from MacOS and onto a AWS EKS (Kubernetes version: 1.14)

**Additional context**
Using Route53 hosted zone for lms domain name. Also, if there is any, then please suggest what can i use instead

**Comment by regisb** [comment]
Hi @RajputVaibhav ! How did you configure object storage? Are you using MinIO? Did you modify its configuration?

**Comment by RajputVaibhav** [comment]
Yes @regisb i used minIO using the command `tutor plugins enable minio`. And made no extra modifications

**Comment by regisb** [comment]
:thinking: and what is the output of `tutor config printvalue MINIO_HOST`?

**Comment by RajputVaibhav** [comment]
minio. followed by the host name I provided

**Comment by regisb** [comment]
Does this minio.<lmshost> domain resolve to anything? If not you will have to modify the MINIO_ HOST configuration parameter.

**Comment by RajputVaibhav** [comment]
Thanks @regisb 
adding a CNAME record for routing *.domain to domain resolved the MINIO_HOST configuration

**Comment by regisb** [comment]
@RajputVaibhav Note that the solution to this problem was clearly mentioned in the docs: https://github.com/overhangio/tutor-minio#dns-records
