### ISSUE TITLE
v3.12.5 - Internal server error

### ISSUE THREAD

**Issue by createinnovative** [overhangio/tutor#329]
**Bug description**

```
<!--  `tutor local logs lms --tail=100` -->

lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
lms_1             |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/utils.py", line 45, in get_as_tags
lms_1             |     bundle = _get_bundle(bundle_name, extension, config)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/utils.py", line 23, in _get_bundle
lms_1             |     bundle = get_loader(config).get_bundle(bundle_name)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/loader.py", line 100, in get_bundle
lms_1             |     "The stats file does not contain valid data. Make sure "
lms_1             | WebpackLoaderBadStatsError: The stats file does not contain valid data. Make sure webpack-bundle-tracker plugin is enabled and try to run webpack again.
lms_1             | 2020-05-21 10:33:44,518 ERROR 36 [django.request] exception.py:135 - Internal Server Error: /
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
lms_1             |     response = get_response(request)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
lms_1             |     response = self._get_response(request)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
lms_1             |     response = self.process_exception_by_middleware(e, request)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
lms_1             |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
lms_1             |     response = view_func(request, *args, **kwargs)
lms_1             |   File "/openedx/edx-platform/common/djangoapps/util/cache.py", line 76, in wrapper
lms_1             |     response = view_func(request, *args, **kwargs)
lms_1             |   File "/openedx/edx-platform/lms/djangoapps/branding/views.py", line 77, in index
lms_1             |     return student.views.index(request, user=request.user)
lms_1             |   File "/openedx/edx-platform/common/djangoapps/student/views/management.py", line 186, in index
lms_1             |     return render_to_response('index.html', context)
lms_1             |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 169, in render_to_response
lms_1             |     return HttpResponse(render_to_string(template_name, dictionary, namespace, request), **kwargs)
lms_1             |   File "/openedx/edx-platform/common/djangoapps/edxmako/shortcuts.py", line 159, in render_to_string
lms_1             |     return template.render(dictionary, request)
lms_1             |   File "/openedx/edx-platform/common/djangoapps/edxmako/template.py", line 59, in render
lms_1             |     return self.mako_template.render_unicode(**context_dictionary)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/mako/template.py", line 454, in render_unicode
lms_1             |     as_unicode=True)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 829, in _render
lms_1             |     **_kwargs_for_callable(callable_, data))
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 864, in _render_context
lms_1             |     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/mako/runtime.py", line 890, in _exec_template
lms_1             |     callable_(context, *args, **kwargs)
lms_1             |   File "/tmp/mako_lms/1374d0592afbffeb77695b71321dcee0/main.html.py", line 220, in render_body
lms_1             |     __M_writer(filters.decode.utf8(static.webpack(entry=u'commons')))
lms_1             |   File "/tmp/mako_lms/1374d0592afbffeb77695b71321dcee0/static_content.html.py", line 288, in render_webpack
lms_1             |     __M_writer(filters.html_escape(filters.decode.utf8(HTML(render_bundle(entry, extension=None, config='DEFAULT', attrs=attrs)))))
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
lms_1             |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/utils.py", line 45, in get_as_tags
lms_1             |     bundle = _get_bundle(bundle_name, extension, config)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/utils.py", line 23, in _get_bundle
lms_1             |     bundle = get_loader(config).get_bundle(bundle_name)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/webpack_loader/loader.py", line 100, in get_bundle
lms_1             |     "The stats file does not contain valid data. Make sure "
lms_1             | WebpackLoaderBadStatsError: The stats file does not contain valid data. Make sure webpack-bundle-tracker plugin is enabled and try to run webpack again.
lms_1             | 172.18.0.2 - - [21/May/2020:10:33:44 +0000] "GET / HTTP/1.0" 500 - "-" "-"
```

**How to reproduce**
sudo curl -L "https://github.com/overhangio/tutor/releases/download/v3.12.5/tutor-$(uname -s)_$(uname -m)" -o /usr/local/bin/tutor
sudo chmod 0755 /usr/local/bin/tutor
tutor local quickstart

I didn't make any changes i just followed the documentation 

**Environment**
i am using ubuntu 18.04

**Comment by regisb** [comment]
Hi @createinnovative ! This issue is similar to #326: it was caused by an error in our CI. This is most annoying, and I really hope to resolve this for real, eventually. Meanwhile, the fix remains the same:

```
tutor images pull openedx
tutor local quickstart
```

Please let me know if the proposed solution does not resolve your issue.

**Comment by createinnovative** [comment]
Thank you very much @regisb

**Comment by createinnovative** [comment]
> Hi @createinnovative ! This issue is similar to #326: it was caused by an error in our CI. This is most annoying, and I really hope to resolve this for real, eventually. Meanwhile, the fix remains the same:
> 
> ```
> tutor images pull openedx
> tutor local quickstart
> ```
> 
> Please let me know if the proposed solution does not resolve your issue.

Thank you @regisb . After applying those commands my site is now working correctly
