### ISSUE TITLE
Error after `Initialising lms...` @ JWT_AUTH["JWT_ISSUER"] = "http://                                     ^ SyntaxError: EOL while scanning string literal

### ISSUE THREAD

**Issue by mavaddat** [overhangio/tutor#330]
**Bug description**
Getting `SyntaxError: EOL while scanning string literal` error on `Initialising lms...`
Here is the (eventual) output of `tutor local quickstart`:
### Start output of `tutor local quickstart`:
```lang-bash
Initialising lms...
docker-compose -f /home/mavaddat/.local/share/tutor/env/local/docker-compose.yml --project-name t
utor_local -f /home/mavaddat/.local/share/tutor/env/local/docker-compose.jobs.yml run --rm lms-jo
b sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms migrate

./manage.py lms create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret avJF3Dc6Ee2DXhNptJjZ7dag \
    --trusted
```
```lang-python
# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```
```lang-bash
2020/05/23 01:38:56 Waiting for: tcp://mysql:3306
2020/05/23 01:38:56 Connected to tcp://mysql:3306
Loading settings lms.envs.tutor.production
Traceback (most recent call last):
  File "./manage.py", line 119, in <module>
    startup = importlib.import_module(edx_args.startup)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/startup.py", line 9, in <module>
    settings.INSTALLED_APPS  # pylint: disable=pointless-statement
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __g
etattr__
    self._setup(name)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _se
tup
    self._wrapped = Settings(settings_module)
  File "/openedx/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __
init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/openedx/edx-platform/lms/envs/tutor/production.py", line 86
    JWT_AUTH["JWT_ISSUER"] = "http://
                                    ^
SyntaxError: EOL while scanning string literal
Error: Command failed with status 1: docker-compose -f /home/mavaddat/.local/share/tutor/env/loca
l/docker-compose.yml --project-name tutor_local -f /home/mavaddat/.local/share/tutor/env/local/do
cker-compose.jobs.yml run --rm lms-job sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s

export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms migrate

./manage.py lms create_oauth2_client \
    "http://androidapp.com" "http://androidapp.com/redirect" public \
    --client_id android --client_secret avJF3Dc6Ee2DXhNptJjZ7dag \
    --trusted
```
```lang-python
# Fix incorrect uploaded file path
if [ -d /openedx/data/uploads/ ]; then
  if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
    echo "Migrating LMS uploaded files to shared directory"
    mv /openedx/data/uploads/* /openedx/media/
    rm -rf /openedx/data/uploads/
  fi
fi
```
### End output of `tutor local quickstart`

Output of `tutor local logs lms --tail=100`:
```
tutor local logs lms --tail=100
docker-compose -f /home/mavaddat/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local logs --tail 100 lms
Attaching to tutor_local_lms_1
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/bin/gunicorn", line 11, in <module>
lms_1             |     sys.exit(run())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
lms_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
lms_1             |     super(Application, self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
lms_1             |     Arbiter(self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
lms_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
lms_1             |     self.stop()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
lms_1             |     time.sleep(0.1)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
lms_1             |     self.reap_workers()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
lms_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
lms_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/bin/gunicorn", line 11, in <module>
lms_1             |     sys.exit(run())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
lms_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
lms_1             |     super(Application, self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
lms_1             |     Arbiter(self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
lms_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
lms_1             |     self.stop()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
lms_1             |     time.sleep(0.1)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
lms_1             |     self.reap_workers()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
lms_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
lms_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/bin/gunicorn", line 11, in <module>
lms_1             |     sys.exit(run())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
lms_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
lms_1             |     super(Application, self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
lms_1             |     Arbiter(self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
lms_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
lms_1             |     self.stop()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
lms_1             |     time.sleep(0.1)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
lms_1             |     self.reap_workers()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
lms_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
lms_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/bin/gunicorn", line 11, in <module>
lms_1             |     sys.exit(run())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
lms_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
lms_1             |     super(Application, self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
lms_1             |     Arbiter(self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
lms_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
lms_1             |     self.stop()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
lms_1             |     time.sleep(0.1)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
lms_1             |     self.reap_workers()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
lms_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
lms_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
lms_1             | Traceback (most recent call last):
lms_1             |   File "/openedx/venv/bin/gunicorn", line 11, in <module>
lms_1             |     sys.exit(run())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
lms_1             |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 166, in run
lms_1             |     super(Application, self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
lms_1             |     Arbiter(self).run()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
lms_1             |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 292, in halt
lms_1             |     self.stop()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 343, in stop
lms_1             |     time.sleep(0.1)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
lms_1             |     self.reap_workers()
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
lms_1             |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
lms_1             | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**How to reproduce**

**Environment**

System

Property  | Value
-- | --
CPUs | Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz (4 x 2990)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onoop_rasterization: disabled_offopengl: enabled_onprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.91GB (1.04GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Linux Ubuntu in WSL2
`Linux DESKTOP 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Docker version 19.03.8, build afacb8b
![image](https://user-images.githubusercontent.com/5055400/82719527-2765d500-9c60-11ea-8965-b29f4d0aa924.png)

**Additional context**

I tried running 
```lang-bash
tutor local stop
sudo rm -rf "$(tutor config printroot)/data/mysql"
tutor local quickstart
```
beforehand, but it ended in the same result.

**Comment by mavaddat** [comment]
I found the issue: I was running `WSL.exe` instead of the distro itself, which was `ubuntu.exe`. `WSL` is just a headless shell I guess.
