### ISSUE TITLE
error in lms job execution

### ISSUE THREAD

**Issue by ramshankar1988** [overhangio/tutor#342]
**Bug description**
getting the following error while doing tutor k8s quickstart 

```
kubectl logs --namespace=openedx --follow $(kubectl get --namespace=openedx pods --selector=job-name=lms-job-20200615182843 -o=jsonpath="{.items[0].metadata.name}")
2020/06/15 18:29:07 Waiting for: tcp://mysql:3306
2020/06/15 18:29:07 Connected to tcp://mysql:3306
Loading settings lms.envs.tutor.production
2020-06-15 18:29:11,006 WARNING 13 [py.warnings] [user None] s3boto.py:48 - /openedx/venv/lib/python3.5/site-packages/storages/backends/s3boto.py:48: DeprecationWarning: The S3BotoStorage backend is deprecated in favor of the S3Boto3Storage backend and will be removed in django-storages 1.8. This backend is mostly in bugfix only mode and has been for quite a while (in much the same way as its underlying library 'boto'). For performance, security and new feature reasons it is _strongly_ recommended that you update to the S3Boto3Storage backend. Please see the migration docs https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#migrating-boto-to-boto3.
  DeprecationWarning

Traceback (most recent call last):
  File "./manage.py", line 120, in <module>
    startup.run()
  File "/openedx/edx-platform/lms/startup.py", line 20, in run
    django.setup()
  File "/openedx/venv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/openedx/venv/lib/python3.5/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/openedx/venv/lib/python3.5/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/pyenv/versions/3.5.9/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/openedx/venv/lib/python3.5/site-packages/edxval/models.py", line 308, in <module>
    class VideoImage(TimeStampedModel):
  File "/openedx/venv/lib/python3.5/site-packages/edxval/models.py", line 313, in VideoImage
    image = CustomizableImageField()
  File "/openedx/venv/lib/python3.5/site-packages/edxval/models.py", line 221, in __init__
    storage=get_video_image_storage(),
  File "/openedx/venv/lib/python3.5/site-packages/edxval/utils.py", line 164, in get_video_image_storage
    )(**settings.VIDEO_IMAGE_SETTINGS.get('STORAGE_KWARGS', {}))
  File "/openedx/venv/lib/python3.5/site-packages/storages/backends/s3boto.py", line 253, in __init__
    check_location(self)
  File "/openedx/venv/lib/python3.5/site-packages/storages/utils.py", line 88, in check_location
    correct,
django.core.exceptions.ImproperlyConfigured: S3BotoStorage.location cannot begin with a leading slash. Found '/openedx/media/'. Use 'openedx/media/' instead.
```

**How to reproduce**
tutor k8s quickstart 
**Environment**
K8S V10.0.1

**Comment by regisb** [comment]
@ramshankar1988 You did enable the `minio` plugin, right? If yes, I'll move this issue to the tutor-minio repository.

**Comment by ramshankar1988** [comment]
No @regisb.
I have not enabled any plugin as of now.
It's a new installation from the scratch.

**Comment by regisb** [comment]
What is the output of the following commands?

```
tutor --version
tutor plugins list
tutor config printvalue OPENEDX_AWS_SECRET_ACCESS_KEY
```

**Comment by ramshankar1988** [comment]
$ tutor --version
tutor, version 10.0.1

$ tutor plugins list
discovery==10.0.0 (disabled)
ecommerce==10.0.0 (disabled)
lts==9.1.6 (disabled)
minio==0.1.5 (disabled)
notes==10.0.0 (disabled)
xqueue==10.0.0 (disabled)

$ tutor config printvalue OPENEDX_AWS_SECRET_ACCESS_KEY
aPaKwEyar4lhmsLOa0l5fChq

**Comment by regisb** [comment]
The fact that OPENEDX_AWS_SECRET_ACCESS_KEY is not empty shows that the minio plugin has been enabled at some point. This is related to issue #241. You should either re-enable it or manually unset the OPENEDX_AWS_SECRET_ACCESS_KEY configuration variable. I recommend the first option, since [minio is required to run Open edX on K8s](https://docs.tutor.overhang.io/k8s.html#s3-like-object-storage-with-minio).
