### ISSUE TITLE
Error while creating user using tutor k8s createuser

### ISSUE THREAD

**Issue by ramshankar1988** [overhangio/tutor#344]
**Bug description**
Getting error while creating the user using tutor k8s createuser command

kubectl exec -i -t --namespace openedx lms-7675df46d5-xhrc8 -- sh -e -c 
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms manage_user  --superuser --staff demo email_id@gmail.com

./manage.py lms changepassword demo

```
Loading settings 
Traceback (most recent call last):
  File "./manage.py", line 120, in <module>
    startup.run()
  File "/openedx/edx-platform/lms/startup.py", line 20, in run
    django.setup()
  File "/openedx/venv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/openedx/venv/lib/python3.5/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/openedx/venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/pyenv/versions/3.5.9/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'debug_toolbar'
command terminated with exit code 1
Error: Command failed with status 1: kubectl exec -i -t --namespace openedx lms-7675df46d5-xhrc8 -- sh -e -c 
echo "Loading settings $DJANGO_SETTINGS_MODULE"

./manage.py lms manage_user  --superuser --staff demo email_id@gmail.com

./manage.py lms changepassword demo
```

**How to reproduce**
tutor k8s createuser --staff --superuser demo email_id@gmail.com

**Environment**
tutor 10.0.7 new installation
Azure AKS
tutor plugins list
discovery==10.0.1 (disabled)
ecommerce==10.0.2 (disabled)
lts==9.1.6 (disabled)
minio==0.1.5 (disabled)
notes==10.0.0 (disabled)
xqueue==10.0.0 (disabled)

**Comment by regisb** [comment]
This is a recent bug and will be fixed in v10.0.8.
