### ISSUE TITLE
Quickstart fails for k8s

### ISSUE THREAD

**Issue by eloff** [overhangio/tutor#345]
**Bug description**

Quickstart fails for kubernetes using microk8s (v=14). Maybe I'm missing a required add-on?

**How to reproduce**

Install microk8s:
sudo snap install microk8s --classic --channel=1.14/stable
microk8s.enable dns storage dashboard ingress

Install tutor.

```➜ tutor k8s quickstart
==================================================
        Interactive platform configuration
==================================================
Are you configuring a production platform? Type 'n' if you are just testing Tutor on your local computer [Y/n] n
As you are not running this platform in production, we automatically set the following configuration values:
    LMS_HOST = local.overhang.io
    CMS_HOST = studio.local.overhang.io
    ACTIVATE_HTTPS = False
Your platform name/title [Dans Edx] 
Your public contact email address [<snip>@gmail.com] 
The default language code for the platform [en] 
Configuration saved to /home/eloff/.local/share/tutor/config.yml
================================================
        Updating the current environment
================================================
Environment generated in /home/eloff/.local/share/tutor/env
=====================================
        Starting the platform
=====================================
kubectl apply --kustomize /home/eloff/.local/share/tutor/env --wait --selector app.kubernetes.io/component=namespace
namespace/openedx unchanged
kubectl apply --kustomize /home/eloff/.local/share/tutor/env --wait --selector app.kubernetes.io/component=volume
persistentvolumeclaim/elasticsearch unchanged
persistentvolumeclaim/minio unchanged
persistentvolumeclaim/mongodb unchanged
persistentvolumeclaim/mysql unchanged
persistentvolumeclaim/rabbitmq unchanged
kubectl apply --kustomize /home/eloff/.local/share/tutor/env --selector app.kubernetes.io/component notin (job, ingress, issuer)
namespace/openedx unchanged
configmap/nginx-config-k45d2dt2k2 unchanged
configmap/openedx-config-g9g7c6925d unchanged
configmap/openedx-settings-cms-4d787b5926 unchanged
configmap/openedx-settings-lms-kb7gdfk4k2 unchanged
service/cms unchanged
service/elasticsearch unchanged
service/forum unchanged
service/lms unchanged
service/memcached unchanged
service/minio unchanged
service/mongodb unchanged
service/mysql unchanged
service/nginx unchanged
service/rabbitmq unchanged
service/smtp unchanged
deployment.apps/cms-worker unchanged
deployment.apps/cms unchanged
deployment.apps/elasticsearch unchanged
deployment.apps/forum configured
deployment.apps/lms-worker unchanged
deployment.apps/lms unchanged
deployment.apps/memcached unchanged
deployment.apps/minio unchanged
deployment.apps/mongodb unchanged
deployment.apps/mysql unchanged
deployment.apps/nginx unchanged
deployment.apps/rabbitmq unchanged
deployment.apps/smtp unchanged
persistentvolumeclaim/elasticsearch unchanged
persistentvolumeclaim/minio unchanged
persistentvolumeclaim/mongodb unchanged
persistentvolumeclaim/mysql unchanged
persistentvolumeclaim/rabbitmq unchanged
================================================
        Database creation and migrations
================================================
Waiting for a mysql pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-QHgPhByL1ndMYAdXM7miWOKh,app.kubernetes.io/name=mysql --for=condition=ContainersReady --timeout=600s pod
pod/mysql-589b445757-l7m8r condition met
Waiting for a elasticsearch pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-QHgPhByL1ndMYAdXM7miWOKh,app.kubernetes.io/name=elasticsearch --for=condition=ContainersReady --timeout=600s pod
pod/elasticsearch-7b57d6cfd7-c4pqg condition met
Waiting for a mongodb pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-QHgPhByL1ndMYAdXM7miWOKh,app.kubernetes.io/name=mongodb --for=condition=ContainersReady --timeout=600s pod
pod/mongodb-57dbcd5557-jcvbb condition met
Initialising all services...
Traceback (most recent call last):
  File "site-packages/urllib3/util/ssl_.py", line 343, in ssl_wrap_socket
ssl.SSLError: unknown error (_ssl.c:3566)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 677, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 381, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
  File "site-packages/urllib3/connection.py", line 370, in connect
  File "site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
urllib3.exceptions.SSLError: unknown error (_ssl.c:3566)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
  File "tutor/commands/cli.py", line 38, in main
  File "site-packages/click/core.py", line 829, in __call__
  File "site-packages/click/core.py", line 782, in main
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1259, in invoke
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 610, in invoke
  File "site-packages/click/decorators.py", line 33, in new_func
  File "tutor/commands/k8s.py", line 39, in quickstart
  File "site-packages/click/decorators.py", line 33, in new_func
  File "tutor/commands/k8s.py", line 127, in init
  File "tutor/scripts.py", line 33, in initialise
  File "tutor/scripts.py", line 18, in run_job_from_template
  File "tutor/commands/k8s.py", line 317, in run_job
  File "tutor/commands/k8s.py", line 286, in active_job_names
  File "site-packages/kubernetes/client/api/batch_v1_api.py", line 671, in list_namespaced_job
  File "site-packages/kubernetes/client/api/batch_v1_api.py", line 773, in list_namespaced_job_with_http_info
  File "site-packages/kubernetes/client/api_client.py", line 345, in call_api
  File "site-packages/kubernetes/client/api_client.py", line 176, in __call_api
  File "site-packages/kubernetes/client/api_client.py", line 366, in request
  File "site-packages/kubernetes/client/rest.py", line 241, in GET
  File "site-packages/kubernetes/client/rest.py", line 214, in request
  File "site-packages/urllib3/request.py", line 76, in request
  File "site-packages/urllib3/request.py", line 97, in request_encode_url
  File "site-packages/urllib3/poolmanager.py", line 336, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 765, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 765, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 765, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 725, in urlopen
  File "site-packages/urllib3/util/retry.py", line 439, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=16443): Max retries exceeded with url: /apis/batch/v1/namespaces/openedx/jobs (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3566)'),))
[79257] Failed to execute script main
```
```
➜ k8s get pods -n openedx
NAME                             READY   STATUS             RESTARTS   AGE
cms-554dc68bb6-nkcvd             1/1     Running            1          27h
cms-worker-74d767c95-9dsdv       1/1     Running            1          27h
elasticsearch-7b57d6cfd7-c4pqg   1/1     Running            1          27h
forum-74db6df458-mscr7           0/1     CrashLoopBackOff   49         27h
lms-5666f95d54-zhfwg             1/1     Running            1          27h
lms-worker-7c745b79d-vs9b7       1/1     Running            1          27h
memcached-758947d664-x7c5j       1/1     Running            1          27h
minio-76456bf89b-bfsf9           1/1     Running            1          27h
mongodb-57dbcd5557-jcvbb         1/1     Running            1          27h
mysql-589b445757-l7m8r           1/1     Running            1          27h
nginx-85cd868bbd-qfqjs           1/1     Running            1          27h
rabbitmq-c5c689879-rt6h7         1/1     Running            1          27h
smtp-fc5d8b4bb-xq9n6             1/1     Running            1          27h
```

```
➜ k8s logs forum-74db6df458-mscr7 -n openedx
Waiting for mongodb/elasticsearch...
2020/06/26 04:15:52 Waiting for: tcp://mongodb:27017
2020/06/26 04:15:52 Waiting for: http://elasticsearch:9200
2020/06/26 04:15:52 Connected to tcp://mongodb:27017
2020/06/26 04:15:52 Received 200 from http://elasticsearch:9200
/openedx/cs_comments_service/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:52: warning: constant ::Fixnum is deprecated
/openedx/cs_comments_service/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-1.1.2/lib/elasticsearch/transport/transport/base.rb:54: warning: constant ::Fixnum is deprecated
W, [2020-06-26T04:15:55.178847 #17]  WARN -- : Overwriting existing field _id in class User.
W, [2020-06-26T04:15:55.233021 #17]  WARN -- : MONGODB | Unsupported client option 'max_retries'. It will be ignored.
W, [2020-06-26T04:15:55.233094 #17]  WARN -- : MONGODB | Unsupported client option 'retry_interval'. It will be ignored.
W, [2020-06-26T04:15:55.233118 #17]  WARN -- : MONGODB | Unsupported client option 'timeout'. It will be ignored.
ERROR: ElasticSearch configuration validation failed. "rake search:validate_index" failed with the following message: Alias 'content' does not exist.
```

**Environment**

Ubuntu 20.04 x86-64

➜ kubectl version (microk8s.kubectl)
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

➜ tutor --version
tutor, version 10.0.8

microk8s.enable dns storage dashboard ingress

➜ docker --version
Docker version 19.03.11, build dd360c7

**Additional Info**

Maybe relevant to the error in the forum service: https://groups.google.com/forum/#!topic/openedx-ops/jsM44XCwJbo

**Comment by regisb** [comment]
This is an issue that occurs while trying to communicate with your K8s cluster. You should be able to replicate it by running:

```
python3
from kubernetes import client, config
config.load_kube_config()
list(client.BatchV1Api().list_namespaced_job("openedx").items)
```

Unfortunately I cannot debug this any further without more information about your K8s cluster. Are you able to investigate this yourself?

**Comment by pravargauba** [comment]
@eloff 
I am also getting similar sort of issue, just with mysql. I am wondering how did you get through mysql installation, that mysql job is waiting for mysql service which is running absolutely fine in another pod, still it throws the error..


```
Configuration saved to /home/pravargauba/.local/share/tutor/config.yml
================================================
        Updating the current environment
================================================
Environment generated in /home/pravargauba/.local/share/tutor/env
=====================================
        Starting the platform
=====================================
kubectl apply --kustomize /home/pravargauba/.local/share/tutor/env --wait --selector app.kubernetes.io/component=namespace
namespace/openedx unchanged
kubectl apply --kustomize /home/pravargauba/.local/share/tutor/env --wait --selector app.kubernetes.io/component=volume
persistentvolumeclaim/elasticsearch unchanged
persistentvolumeclaim/mongodb unchanged
persistentvolumeclaim/mysql unchanged
persistentvolumeclaim/rabbitmq unchanged
kubectl apply --kustomize /home/pravargauba/.local/share/tutor/env --selector app.kubernetes.io/component notin (job, ingress, issuer)
namespace/openedx unchanged
configmap/nginx-config-fhtftdtbt6 unchanged
configmap/openedx-config-h78m9t5hgc unchanged
configmap/openedx-settings-cms-72tffc448k unchanged
configmap/openedx-settings-lms-g5thf28t9m unchanged
service/cms unchanged
service/elasticsearch unchanged
service/forum unchanged
service/lms unchanged
service/memcached unchanged
service/mongodb unchanged
service/mysql unchanged
service/nginx unchanged
service/rabbitmq unchanged
service/smtp unchanged
deployment.apps/cms-worker unchanged
deployment.apps/cms unchanged
deployment.apps/elasticsearch unchanged
deployment.apps/forum configured
deployment.apps/lms-worker unchanged
deployment.apps/lms unchanged
deployment.apps/memcached unchanged
deployment.apps/mongodb unchanged
deployment.apps/mysql unchanged
deployment.apps/nginx unchanged
deployment.apps/rabbitmq unchanged
deployment.apps/smtp unchanged
persistentvolumeclaim/elasticsearch unchanged
persistentvolumeclaim/mongodb unchanged
persistentvolumeclaim/mysql unchanged
persistentvolumeclaim/rabbitmq unchanged
================================================
        Database creation and migrations
================================================
Waiting for a mysql pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-C9RPlMf6zqHkgSeJeATajfM8,app.kubernetes.io/name=mysql --for=condition=ContainersReady --timeout=600s pod
pod/mysql-5995df95cc-dzft8 condition met
Waiting for a elasticsearch pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-C9RPlMf6zqHkgSeJeATajfM8,app.kubernetes.io/name=elasticsearch --for=condition=ContainersReady --timeout=600s pod
pod/elasticsearch-858854fdbd-hx5jr condition met
Waiting for a mongodb pod to be ready...
kubectl wait --namespace openedx --selector=app.kubernetes.io/instance=openedx-C9RPlMf6zqHkgSeJeATajfM8,app.kubernetes.io/name=mongodb --for=condition=ContainersReady --timeout=600s pod
pod/mongodb-5d4c9cb748-6lnc8 condition met
Initialising all services...
kubectl apply --kustomize /home/pravargauba/.local/share/tutor/env --selector app.kubernetes.io/name=mysql-job-20200710212708
job.batch/mysql-job-20200710212708 created
Job mysql-job-20200710212708 is running. To view the logs from this job, run:

    kubectl logs --namespace=openedx --follow $(kubectl get --namespace=openedx pods --selector=job-name=mysql-job-20200710212708 -o=jsonpath="{.items[0].metadata.name}")

Waiting for job completion...
```
Here are the number of pods running.
```
pravargauba@openedx-tutor-vm:~/.local/share/tutor/env/k8s$ kubectl get pods -n openedx
NAME                             READY   STATUS             RESTARTS   AGE
cms-7f5cc4c89c-hrjz4             1/1     Running            1          6m20s
cms-worker-57d6cb49f6-plkv9      1/1     Running            0          6m20s
elasticsearch-858854fdbd-hx5jr   1/1     Running            0          6m20s
forum-6f475f67c4-n9j6f           0/1     CrashLoopBackOff   5          6m20s
lms-8fcbb986f-blkmj              1/1     Running            0          6m19s
lms-worker-7784cbdb55-vnght      1/1     Running            0          6m20s
memcached-66ff584747-h6hxs       1/1     Running            0          6m20s
mongodb-5d4c9cb748-6lnc8         1/1     Running            0          6m19s
mysql-5995df95cc-dzft8           1/1     Running            0          6m19s
mysql-job-20200710212708-r66mt   1/1     Running            0          5m34s
nginx-675d956464-d2cnq           1/1     Running            0          6m19s
rabbitmq-7794f78f66-pbp49        1/1     Running            0          6m19s
smtp-5c6f8d7fd7-gts7x            1/1     Running            0          6m19s
```
here are the mysql pod logs, which according to me is running fine.

```
pravargauba@openedx-tutor-vm:~/.local/share/tutor/env/k8s$ kubectl logs mysql-5995df95cc-dzft8 -n openedx
2020-07-10 21:26:39 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2020-07-10 21:26:40 0 [Note] mysqld (mysqld 5.6.36) starting as process 1 .
```

I also tried removing /data/mysql from the tutor printroot directory, and did ``tutor k8s quickstart``  to initialize db's back again, still no luck.

**Comment by regisb** [comment]
@pravargauba I fail to see how your error is related to this one. If you have issues getting `tutor k8s` to run I encourage you to discuss this on the [forums](https://discuss.overhang.io), as suggested in the [troubleshooting sections of the docs](docs.tutor.overhang.io/troubleshooting.html). If we do identify a bug then we'll open a Github issue.

@eloff Since you did not reply to my last comment I'll close this for now.
