### ISSUE TITLE
macOS M1: OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

### ISSUE THREAD

**Issue by lpm0073** [overhangio/tutor#496]
**Bug description**

I spent much of this weekend looking for a macOS-specific solution to this problem that would not involve modifying Tutor but i think i've exhausted all possibilities.

#26 95.44   Downloading Shapely-1.7.1.tar.gz (383 kB)
#26 95.71     ERROR: Command errored out with exit status 1:
#26 95.71      command: /openedx/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4fla8rzl/shapely/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4fla8rzl/shapely/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4fla8rzl/shapely/pip-egg-info
#26 95.71          cwd: /tmp/pip-install-4fla8rzl/shapely/
#26 95.71     Complete output (11 lines):
#26 95.71     Failed `CDLL(libgeos_c.so.1)`
#26 95.71     Failed `CDLL(libgeos_c.so)`
#26 95.71     Traceback (most recent call last):
#26 95.71       File "<string>", line 1, in <module>
#26 95.71       File "/tmp/pip-install-4fla8rzl/shapely/setup.py", line 85, in <module>
#26 95.71         from shapely._buildcfg import geos_version_string, geos_version, \
#26 95.71       File "/tmp/pip-install-4fla8rzl/shapely/shapely/_buildcfg.py", line 169, in <module>
#26 95.71         lgeos = load_dll('geos_c',
#26 95.71       File "/tmp/pip-install-4fla8rzl/shapely/shapely/_buildcfg.py", line 162, in load_dll
#26 95.71         raise OSError(
#26 95.71     OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
#26 95.71     ----------------------------------------

Following are three relevant posts that fully explain the origin of the problem:
1.) https://stackoverflow.com/questions/19742406/could-not-find-library-geos-c-or-load-any-of-its-variants
2.) https://stackoverflow.com/questions/64963370/error-cannot-install-in-homebrew-on-arm-processor-in-intel-default-prefix-usr
3.) https://github.com/Toblerity/Shapely/issues/1080

Briefly summarizing: the PyPi package Shapely does not yet support native wheel on Apple Silicon and therefore must be installed using an 86_64 Rosetta 2 version of Homebrew. Additionally the following two environment variables need to be set: 
 - DYLD_LIBRARY_PATH="/usr/local/homebrew/Cellar/geos/3.9.1/include:/usr/local/homebrew/Cellar/geos/3.9.1/lib:$LD_LIBRARY_PATH"
 - GEOS_CONFIG="/usr/local/homebrew/Cellar/geos/3.9.1/bin/geos-config"
Noting however that these environment variables need to be visible from within the virtual environment that Docker creates for the openedx build, which is where i am presently stuck.

**How to reproduce**
on macOS M1:
1. start the docker service: 
2. ensure that Docker app preference include "Preferences / Experimental Features / Use Docker Compose"
3. ensure that you have not pip-installed docker-compose or installed it any other way
4. $ tutor local build openedx

**Environment**

- macOS Big Sur 11.6 on Mac mini (M1, 2020), 8GB memory.
- docker desktop Engine 20.10.7 with "Preferences / Experimental Features / Use Docker Compose"
- Tutor is installed in a virtual environment running Python 3.9.6 and pip version 21.2.4

**Additional context**

**Comment by lpm0073** [comment]
I was able to resolve this without making any modifications to Tutor. Summarizing: in macOS M1 there are a couple of dozen packages that need to be installed with Homebrew, and, multiple environment variables need to be set for many of these packages in order for cython and bcc to find header files and libraries.

i pushed my macOS configuration files to this location: https://github.com/lpm0073/edx.scripts/tree/master/macos/m1

Additionally, and specific to the Lilac release, some of the requirements package versions have to be bumped due to problems that were introduced with the release of Apple Silicon. These packages are: xmlsec, cryptography, and numpy. The exact changes are recorded here, in these two commits:
 - https://github.com/lpm0073/edx-platform/commit/89c4dfcdb4957bdf1e866751b06979f800b1a918
 - https://github.com/lpm0073/edx-platform/commit/c6a4e5b717096383400d6db13079dcf6167a63c9
edx-platform master branch on the other hand builds without any problems. 

Final comment: based on recommendations from the SciPy web site i switched to using Homebrew's release of Python 3.8 from the macOS pre-installed version. If you're not already using this release of Python then you should consider switching. I get more consistent results with the Homebrew release.
