### ISSUE TITLE
Unit test fails on Mac

### ISSUE THREAD

**Issue by nedbat** [overhangio/tutor#560]
**Bug description**

I ran `make test-unit` on my Mac:
```
% make test-unit
python -m unittest discover tests
.....................................................................................................F..................
======================================================================
FAIL: test_check_macos_memory_darwin_filenotfound (test_utils.UtilsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/pyenv/pyenv/versions/3.8.12/lib/python3.8/unittest/mock.py", line 1325, in patched
    return func(*newargs, **newkeywargs)
  File "/System/Volumes/Data/root/src/edx/tutor/tests/test_utils.py", line 160, in test_check_macos_memory_darwin_filenotfound
    self.assertRaises(exceptions.TutorError, utils.check_macos_memory)
AssertionError: TutorError not raised by check_macos_memory

----------------------------------------------------------------------
Ran 120 tests in 27.334s

FAILED (failures=1)
make: *** [test-unit] Error 1
```

I see what's happening: the test assumes check_macos_memory will fail because it can't find the settings file, because it assumes the tests are being run on Linux.  On my Mac, it finds the file, and confirms the setting is good, so the function doesn't fail.

Do you want the tests to be runnable on a Mac?

**Environment**
macOS 10.15.7

**Comment by regisb** [comment]
We definitely want the tests to run properly on macOS. I opened a PR to address this issue: https://github.com/overhangio/tutor/pull/561
