### ISSUE TITLE
SAML Plugin Example fails

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#601]
**Bug description**
in the readme docs, the example for the SAML Plugin leads to a server error. 

```
Traceback (most recent call last):
File "lms/wsgi.py", line 19, in <module>
startup.run()
File "/openedx/edx-platform/./lms/startup.py", line 20, in run
django.setup()
File "/openedx/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
apps.populate(settings.INSTALLED_APPS)
File "/openedx/venv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
app_config.import_models()
File "/openedx/venv/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
self.models_module = import_module(models_module_name)
File "/opt/pyenv/versions/3.8.12/lib/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 843, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/openedx/edx-platform/common/djangoapps/third_party_auth/models.py", line 50, in <module>
_PSA_BACKENDS = {backend_class.name: backend_class for backend_class in _load_backend_classes()}
File "/openedx/edx-platform/common/djangoapps/third_party_auth/models.py", line 50, in <dictcomp>
_PSA_BACKENDS = {backend_class.name: backend_class for backend_class in _load_backend_classes()}
File "/openedx/edx-platform/common/djangoapps/third_party_auth/models.py", line 47, in _load_backend_classes
auth_class = module_member(class_path)
File "/openedx/venv/lib/python3.8/site-packages/social_core/utils.py", line 59, in module_member
module = import_module(mod)
File "/openedx/venv/lib/python3.8/site-packages/social_core/utils.py", line 53, in import_module
__import__(name)
ModuleNotFoundError: No module named 'third_party_auth' 
``` 

**How to reproduce**
use this plugin, save the configs and start.
```
name: saml
version: 0.1.0
patches:
  common-env-features: |
    "ENABLE_THIRD_PARTY_AUTH": true

  openedx-lms-common-settings: |
    # saml special settings
    AUTHENTICATION_BACKENDS += ["third_party_auth.saml.SAMLAuthBackend", "django.contrib.auth.backends.ModelBackend"]
``` 

**Environment**
OS: Ubuntu 20.04
Tutor: 13.1.3

**Comment by BbrSofiane** [comment]
This issue can be closed with https://github.com/overhangio/tutor/commit/2cf4e6dc3877aafd1b4c7b282275c7d6f467625e
