### ISSUE TITLE
16.1.6 release appears to have broken contrib plugins

### ISSUE THREAD

**Issue by fghaas** [overhangio/tutor#943]
**Bug description**

Bumping the dependency on `tutor` to `>=16.1.6` in our retirement contrib plugin (see https://github.com/hastexo/tutor-contrib-retirement/pull/27) breaks our build:

```
py38: install_package_deps> python -I -m pip install 'tutor<17,>=16.1.6'
Collecting tutor<17,>=16.1.6
  Downloading tutor-16.1.6.tar.gz (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.1/117.1 kB 4.3 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
py38: exit 1 (2.88 seconds) /home/runner/work/tutor-contrib-retirement/tutor-contrib-retirement> python -I -m pip install 'tutor<17,>=16.1.6' pid=2003
.pkg: _exit> python /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py38: FAIL ✖ in 6.26 seconds
flake8: install_deps> python -I -m pip install flake8
flake8: freeze> python -m pip freeze --all
flake8: flake8==6.1.0,mccabe==0.7.0,pip==23.3.1,pycodestyle==2.11.1,pyflakes==3.1.0,setuptools==68.2.2,wheel==0.41.2
tox: flake8
  gitlint: OK (3.06=setup[2.94]+cmd[0.12] seconds)
  py38: FAIL code 1 (6.26 seconds)
  
  flake8: OK (2.13=setup[1.87]+cmd[0.26] seconds)
  evaluation failed :( (11.53 seconds)
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/runner/work/tutor-contrib-retirement/tutor-contrib-retirement/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/runner/work/tutor-contrib-retirement/tutor-contrib-retirement/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/runner/work/tutor-contrib-retirement/tutor-contrib-retirement/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-0fdttx2a/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-0fdttx2a/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0fdttx2a/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-0fdttx2a/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 62, in <module>
        File "<string>", line 29, in load_requirements
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-0ea_1nlb/tutor_41909c4854ad4354a9f1d9de33aba6bc/requirements/dev.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

Looks like that `dev.txt` file didn't make it into the `tutor` package as published on PyPI.

See [the full build log](https://github.com/hastexo/tutor-contrib-retirement/actions/runs/6901724375/job/18777049075#step:5:80) for further context.

**How to reproduce**

```bash
git clone https://github.com/fghaas/tutor-contrib-retirement/tree/palm.4
cd tutor-contrib-retirement
tox -r
```

**Comment by regisb** [comment]
Thank you so much for raising this issue quickly Florian. I'll publish 16.1.7 right away.

**Comment by sambapete** [comment]
It's probably related but I have a similar issue trying to install tutor with

**Comment by fghaas** [comment]
Thanks @regisb!
